lua require('tree')
lua require('plugins')
lua require('basic')
lua require('search')
lua require('git')
lua require('language')
lua require('binds')
lua require('opts.slime')
lua require('theme')
lua require('lualine_conf')
" lua require('treesitter')
lua require('fzf')
